### ISSUE TITLE
Feature: non-dichotomous trait table

### ISSUE THREAD

**Issue by rbutleriii** [AdmiralenOla/Scoary#26]
I am looking at a particular trait (heat resistance) across a set of strains of a given species, and I was wondering if it would be possible to examine a continuous variation in the trait (normalized from 0-1?) or a discrete set of values (low, medium, high? preferably more = better).

Thanks

**Comment by AdmiralenOla** [comment]
Unfortunately you can't use Scoary to analyze a continuous trait per se, but you can break your phenotype into multiple categories. In your example, you could dichotomize your input data so that one phenotype was low versus medium/high and a second one low/medium versus high. This would preserve the ordinal relationship between your categories, but could potentially inflate the number of false positive results you find.

I'd like to get around to implementing support for true continuous variables eventually, but this would require some very major changes to the algorithm so it's probably not going to happen in the near future. Sorry!

**Comment by rbutleriii** [comment]
Makes sense, I will give it a try.
