### ISSUE TITLE
VCF GWAS

### ISSUE THREAD

**Issue by ahmedmagds** [AdmiralenOla/Scoary#76]
How do I use multiple vcf files to create the Scoary csv to be used with the the main script? Or in other words if I start with multiple vcf files of different isolates mapped to the same reference, how can I get scoary results (similar to starting from roary).

**Comment by AdmiralenOla** [comment]
Hi @ahmedmagds,

Replying way too late to your question. Sorry. You should be able to merge your VCF files using bcftools merge. You should then be able to run Scoary's vcf2scoary script on this merged VCF file. Note that this script is very much in beta version, and I'd appreciate bug reports. The file you get from vcf2scoary can be used instead of a gene_presence_absence.csv file from Roary. Note that you have to specify the correct start column (-s) when you run Scoary.

**Comment by ahmedmagds** [comment]
Thanks @AdmiralenOla !
