### ISSUE TITLE
Empty output files with k-mer GWAS

### ISSUE THREAD

**Issue by npavlovikj** [AdmiralenOla/Scoary#81]
Hi,

I am running Scoary with manually created k-mer file. While the job finishes ok, the output file is empty, and I don't see any errors. I have 60 different datasets for which the same occurs, so I believe I am either misusing the options, not properly formatting the k-mer file, or exceeding the array. 

I used Scoary 1.6.16 with Python 3.6 installed using conda, and the command I use is:
```
scoary -s 2 -t gr1.csv -g gr1_matrix_kmer.csv --threads 16 \
    -o scoary_out_gr1 --delimiter ',' -c I EPW
```

"gr1.csv" has 1077 rows and looks like:
```
,serovar_phenotype
DRR106950,0
ERR023784,0
```
while "gr1_matrix_kmer.csv" has 1077 columns and 718522 rows, where the first column is the k-mer, and remaining columns are the samples (thus the `-s 2` option).

I would really appreciate your input on this. If you need any additional information, or you have any ideas why I am not getting any output, please let me know.

Thank you,
Natasha

**Comment by AdmiralenOla** [comment]
Hi Natasha,

Sounds strange. Could you try running with -p 1.0 to check that your results aren't simply being filtered due to having a Fisher p-value >=0.05?

If that doesn't work I would gladly take a look at your files if you send them to me at olbb@fhi.no (You can just do a tiny subset of the rows in the kmer presence/absence file)
