### ISSUE TITLE
/var/spool/gridengine/execd/cu17/job_scripts/371921: line 11:  9884 Killed   

### ISSUE THREAD

**Issue by 971202** [AdmiralenOla/Scoary#92]
/var/spool/gridengine/execd/cu17/job_scripts/371921: line 11:  9884 Killed                  /gluster/home/yangtao/miniconda3/bin/scoary -g /gluster/home/yangtao/zhihe_seq/velvet/contigs/prokka/b/chrom/gene_presence_absence1.csv -t /gluster/home/yangtao/zhihe_seq/velvet/contigs/prokka/b/chrom/trait1.csv

there is no result

**Comment by AdmiralenOla** [comment]
Dear @971202 ,

Sorry but this is not enough for me to diagnose your error. It looks like your job was killed, but there could be thousands of reasons why this happens. Are you getting an error message? Could you check your log file from Scoary?

Since this issue does not pertain to any particular error or question I will close it for now.
